=== LitterMonster/Cloud-note-submit/data/restrict.dtd
<?xml version="1.0"?>
<!ELEMENT notes (message+)>
<!ELEMENT message(name,time,content,picture)>
<!ELEMENT name(#PCDATA)>
<!ELEMENT time(#PCDATA)>
<!ELEMENT content(#PCDATA)>
<!ELEMENT picture(#PCDATA)>

=== LitterMonster/Cloud-note-submit/data/20134833457.xml
<?xml version="1.0"?>
<!DOCTYPE notes SYSTEM "restrict.dtd">
<notes>

    <message><name>&#x7F8E;&#x4E3D;&#x7684;&#x6781;&#x5149;</name><time>1450871657</time><content>&#x8FD9;&#x7A0D;&#x7EB5;&#x5373;&#x901D;&#x7684;&#x6781;&#x5149;&#x50CF;&#x6781;&#x4E86;&#x6211;&#x4EEC;&#x767D;&#x9A79;&#x8FC7;&#x9699;&#x822C;&#x7684;&#x4EBA;&#x751F;&#x3002;</content><picture>1450871657.jpg</picture></message><message><name>&#x51B0;&#x6CB3;</name><time>1450873216</time><content>&#x51B0;&#x6CB3;</content><picture>1450873216.jpg</picture></message><message><name>&#x6C34;&#x5929;&#x4E00;&#x7EBF;</name><time>1450873248</time><content>&#x6C34;&#x5929;&#x4E00;&#x7EBF;</content><picture>1450873248.jpg</picture></message><message><name>&#x5927;&#x6D77;</name><time>1450873299</time><content>&#x6CE2;&#x6F9C;&#x58EE;&#x9614;&#x7684;&#x5927;&#x6D77;</content><picture>1450873299.jpg</picture></message><message><name>&#x5BCC;&#x58EB;&#x5C71;</name><time>1450873344</time><content>&#x5BCC;&#x58EB;&#x5C71;</content><picture>1450873344.jpg</picture></message><message><name>&#x6C34;&#x7EB9;</name><time>1450873597</time><content>&#x6C34;&#x7EB9;</content><picture>1450873597.jpg</picture></message><message><name>&#x9EC4;&#x660F;</name><time>1450873637</time><content>&#x9EC4;&#x660F;</content><picture>1450873637.jpg</picture></message><message><name>&#x8FD9;&#x91CC;&#x6CA1;&#x6709;&#x56FE;&#x7247;</name><time>1450873662</time><content>&#x8FD9;&#x91CC;&#x6CA1;&#x6709;&#x56FE;&#x7247;</content><picture>no_pic.jpg</picture></message><message><name>&#x5DCD;&#x5CE8;&#x7684;&#x5C71;&#x5CF0;</name><time>1450875056</time><content>&#x5DCD;&#x5CE8;&#x7684;&#x5C71;&#x5CF0;&#x554A;&#xFF01;</content><picture>1450875056.jpg</picture></message></notes>
